import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import { ClaimStatusBadge } from '@/components/claims/ClaimStatusBadge'
import { PageHeader } from '@/components/layout/PageHeader'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { getClaimsByPolicyId, type AgentClaimWithCustomer } from '@/services/claimsService'
import { getCustomerWithProfile, type CustomerWithProfile } from '@/services/customerService'
import { getPolicyWithCustomer, type PolicyWithCustomer } from '@/services/policyService'
import { formatCurrency, formatDate } from '@/utils/formatters'

export default function AgentPolicyDetailsPage() { const { policyId } = useParams<{ policyId: string }>(); const [policy, setPolicy] = useState<PolicyWithCustomer | null>(null); const [customer, setCustomer] = useState<CustomerWithProfile | null>(null); const [claims, setClaims] = useState<AgentClaimWithCustomer[]>([]); useEffect(() => { void (async () => { if (!policyId) return; const found = await getPolicyWithCustomer(policyId); setPolicy(found); if (found) { setCustomer(await getCustomerWithProfile(found.customerId)); setClaims(await getClaimsByPolicyId(found.id)) } })() }, [policyId]); if (!policy) return <div className="space-y-4"><Button asChild variant="ghost"><Link to="/agent/policies"><ArrowLeft /> Policies</Link></Button><p className="text-sm text-muted-foreground">Policy not found.</p></div>; return <div className="space-y-6"><PageHeader title={policy.policyNumber} description={policy.type} /><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Policy information</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2"><p><b>Coverage</b><br />{formatCurrency(policy.coverageAmount)}</p><p><b>Premium</b><br />{formatCurrency(policy.premium)}</p><p><b>Status</b><br /><span className="capitalize">{policy.status}</span></p><p><b>Period</b><br />{formatDate(policy.startDate)} – {formatDate(policy.endDate)}</p></CardContent></Card><Card><CardHeader><CardTitle>Customer</CardTitle></CardHeader><CardContent className="text-sm"><p className="font-medium">{customer?.user.firstName} {customer?.user.lastName}</p><p>{customer?.user.email}</p><p>{customer?.phone}</p>{customer && <Button asChild variant="link" className="mt-2 px-0"><Link to={`/agent/customers/${customer.id}`}>View customer</Link></Button>}</CardContent></Card></div><Card><CardHeader><CardTitle>Related claims</CardTitle></CardHeader><CardContent className="space-y-3">{claims.length ? claims.map((claim) => <div key={claim.id} className="flex items-center justify-between gap-3 border-b pb-3 text-sm"><div><b>{claim.claimNumber}</b><p className="text-muted-foreground">{formatCurrency(claim.claimAmount)} · {formatDate(claim.submittedAt)}</p></div><div className="flex gap-2"><ClaimStatusBadge status={claim.status} /><Button asChild variant="ghost" size="sm"><Link to={`/agent/claims/${claim.id}`}>Review</Link></Button></div></div>) : <p className="text-sm text-muted-foreground">No related claims.</p>}</CardContent></Card></div> }
