import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import { ClaimStatusBadge } from '@/components/claims/ClaimStatusBadge'
import { PageHeader } from '@/components/layout/PageHeader'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { getClaimsByCustomerId, type ClaimWithPolicy } from '@/services/claimsService'
import { getCustomerWithProfile, type CustomerWithProfile } from '@/services/customerService'
import { getPoliciesByCustomerId } from '@/services/policyService'
import type { Policy } from '@/types'
import { formatCurrency, formatDate } from '@/utils/formatters'

export default function AgentCustomerDetailsPage() { const { customerId } = useParams<{ customerId: string }>(); const [customer, setCustomer] = useState<CustomerWithProfile | null>(null); const [policies, setPolicies] = useState<Policy[]>([]); const [claims, setClaims] = useState<ClaimWithPolicy[]>([]); useEffect(() => { void (async () => { if (!customerId) return; const profile = await getCustomerWithProfile(customerId); setCustomer(profile); if (profile) { setPolicies(await getPoliciesByCustomerId(profile.id)); setClaims(await getClaimsByCustomerId(profile.id)) } })() }, [customerId]); if (!customer) return <div className="space-y-4"><Button asChild variant="ghost"><Link to="/agent/customers"><ArrowLeft /> Customers</Link></Button><p className="text-sm text-muted-foreground">Customer not found.</p></div>; return <div className="space-y-6"><PageHeader title={`${customer.user.firstName} ${customer.user.lastName}`} description="Customer profile, coverage, and claims history." /><Card><CardContent className="grid gap-4 p-6 sm:grid-cols-2"><p><b>Email</b><br />{customer.user.email}</p><p><b>Phone</b><br />{customer.phone}</p><p className="sm:col-span-2"><b>Address</b><br />{customer.address}</p></CardContent></Card><Card><CardHeader><CardTitle>Policies</CardTitle></CardHeader><CardContent className="space-y-3">{policies.map((policy) => <div key={policy.id} className="flex items-center justify-between border-b pb-3 text-sm"><div><b>{policy.policyNumber}</b> · {policy.type}<p className="text-muted-foreground">{formatCurrency(policy.coverageAmount)} · {formatDate(policy.endDate)}</p></div><Button asChild variant="ghost" size="sm"><Link to={`/agent/policies/${policy.id}`}>View</Link></Button></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Claims</CardTitle></CardHeader><CardContent className="space-y-3">{claims.map((claim) => <div key={claim.id} className="flex items-center justify-between gap-3 border-b pb-3 text-sm"><div><b>{claim.claimNumber}</b> · {claim.policyType}<p className="text-muted-foreground">{formatCurrency(claim.claimAmount)} · {formatDate(claim.submittedAt)}</p></div><div className="flex items-center gap-2"><ClaimStatusBadge status={claim.status} /><Button asChild variant="ghost" size="sm"><Link to={`/agent/claims/${claim.id}`}>Review</Link></Button></div></div>)}</CardContent></Card></div> }
